---
fqs:
  9331.1.128793.CGAGGCT-CTCTCTA.fastq.gz:
    library: libName
    organism: Escherichia	coli	TOP10
    rg_id: 9331.1.128793.CGAGGCT-CTCTCTA
    rg_sample_name: ANXHX_libName
    src_path: /Users/mwornow-m/Desktop/seqval/SMBMiSeqData/9331.1.128793.CGAGGCT-CTCTCTA.fastq.gz
ref_faidx: /Users/mwornow-m/Desktop/JBEIseqval/MiSeqValidationResults/ANZPH/ref/references.fasta.fai
ref_fasta: /Users/mwornow-m/Desktop/JBEIseqval/MiSeqValidationResults/ANZPH/ref/references.fasta
